# Set the maximum line length for formatter
line-length = 120

# Assume Python 3.8
target-version = "py38"

# Enable --fix behavior by-default
fix = true

[lint]
task-tags = ["TODO", "COMMAND"]

# On top of the default `select` ("E4", "E7", "E9", "F") add isort ("I")
extend-select = ["I", "D"]

# Ignore E712 - Comparison to `False` should be `cond is False` or `if not cond' - not applicable for pyspark dfs
# Ignore F821 - Ignore undefined names inherited from other notebook runs
# extend-ignore = ["E402", "E712", "F821"]
extend-ignore = [
    "D", # NOTE: Remove once we'll have time to properly document all functions
    "E731", # ignore error for assigning lambda expressions
    "D104", # disable  package level doc strings
    "D107", # disable __init__ level docstrings
    "D105", # disable dunder(magic) functions level docstring
    "D415", # disable requirement for first line to end on . , ! ?
    "D205", # disable 1 blank line after summary requirement
] 


[lint.isort]
force-sort-within-sections = true  # Don't group `from` imports separately
order-by-type = true  # Order by CONSTANT, CamelCase, snake_case